// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod thoth {
    pub mod plugin {
        /// ---------------------------------------------------------------------------
        /// Shared types — imported by every interface below
        /// ---------------------------------------------------------------------------
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Maps from src/wit/mod.rs `Capabilities` enum.
            /// Declare which of these your plugin implements in `plugin-info`.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Capability {
                FileLoader,
                FileViewer,
                DataSource,
                Exporter,
                SearchProvider,
                NewUiComponent,
            }
            impl ::core::fmt::Debug for Capability {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Capability::FileLoader => {
                            f.debug_tuple("Capability::FileLoader").finish()
                        }
                        Capability::FileViewer => {
                            f.debug_tuple("Capability::FileViewer").finish()
                        }
                        Capability::DataSource => {
                            f.debug_tuple("Capability::DataSource").finish()
                        }
                        Capability::Exporter => {
                            f.debug_tuple("Capability::Exporter").finish()
                        }
                        Capability::SearchProvider => {
                            f.debug_tuple("Capability::SearchProvider").finish()
                        }
                        Capability::NewUiComponent => {
                            f.debug_tuple("Capability::NewUiComponent").finish()
                        }
                    }
                }
            }
            impl Capability {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Capability {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Capability::FileLoader,
                        1 => Capability::FileViewer,
                        2 => Capability::DataSource,
                        3 => Capability::Exporter,
                        4 => Capability::SearchProvider,
                        5 => Capability::NewUiComponent,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Maps from src/wit/mod.rs `Plugin` struct.
            /// `location` is intentionally absent here — it is set by the host at
            /// discovery time (the path where the .wasm file lives) and is not
            /// something the plugin itself knows or declares.
            #[derive(Clone)]
            pub struct PluginInfo {
                pub id: _rt::String,
                /// reverse-domain unique id, e.g. "com.example.csv-loader"
                pub name: _rt::String,
                /// human-readable, e.g. "CSV Loader"
                pub version: _rt::String,
                /// semver string, e.g. "0.2.1"
                pub description: _rt::String,
                pub capabilities: _rt::Vec<Capability>,
                pub author: Option<_rt::String>,
                pub homepage: Option<_rt::String>,
                /// Sidebar icon glyph. Use a phosphor icon Unicode character (e.g. "\u{E28C}").
                /// Falls back to a generic database icon when absent.
                pub icon: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for PluginInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginInfo")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("description", &self.description)
                        .field("capabilities", &self.capabilities)
                        .field("author", &self.author)
                        .field("homepage", &self.homepage)
                        .field("icon", &self.icon)
                        .finish()
                }
            }
            /// Unified error type used across all interfaces.
            #[derive(Clone)]
            pub struct PluginError {
                pub code: u32,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginError")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod thoth {
        pub mod plugin {
            /// ---------------------------------------------------------------------------
            /// file-loader — implement when capability = file-loader
            ///
            /// Teaches Thoth to open a new file format. The host calls open() once,
            /// then calls get() lazily as the user scrolls. Maps to the core
            /// `FileLoader` trait in src/file/loaders/mod.rs.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod file_loader {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_supported_extensions_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::supported_extensions();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = result0;
                    let len3 = vec3.len();
                    let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result3 = if layout3.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout3);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec3.into_iter().enumerate() {
                        let base = result3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = result3;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_supported_extensions<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_open_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::open(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr2.add(8).cast::<i64>() = _rt::as_i64(e);
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code3,
                                message: message3,
                            } = e;
                            *ptr2.add(8).cast::<i32>() = _rt::as_i32(code3);
                            let vec4 = (message3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_open<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_cabi<T: Guest>(arg0: i64) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get(arg0 as u64);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code3,
                                message: message3,
                            } = e;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code3);
                            let vec4 = (message3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_raw_bytes_cabi<T: Guest>(arg0: i64) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::raw_bytes(arg0 as u64);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code3,
                                message: message3,
                            } = e;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code3);
                            let vec4 = (message3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_raw_bytes<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// File extensions this plugin handles, without the leading dot.
                    /// e.g. ["csv", "tsv"]
                    fn supported_extensions() -> _rt::Vec<_rt::String>;
                    /// Open the file at `path` and index it. Do NOT load all records into
                    /// memory — just prepare for lazy access.
                    /// Returns the total number of records (rows, objects, etc.) in the file.
                    fn open(path: _rt::String) -> Result<u64, PluginError>;
                    /// Return the record at `idx` serialised as a JSON string.
                    /// Called lazily as the user scrolls — must be fast and stateless.
                    fn get(idx: u64) -> Result<_rt::String, PluginError>;
                    /// Return the raw bytes of the record at `idx` without JSON parsing.
                    /// Used by the copy-to-clipboard and export paths.
                    fn raw_bytes(idx: u64) -> Result<_rt::Vec<u8>, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_file_loader_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/file-loader@0.1.0#supported-extensions")] unsafe
                        extern "C" fn export_supported_extensions() -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_supported_extensions_cabi::<$ty >
                        () } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/file-loader@0.1.0#supported-extensions")]
                        unsafe extern "C" fn _post_return_supported_extensions(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_supported_extensions::<$ty > (arg0) } } #[unsafe
                        (export_name = "thoth:plugin/file-loader@0.1.0#open")] unsafe
                        extern "C" fn export_open(arg0 : * mut u8, arg1 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*:: _export_open_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/file-loader@0.1.0#open")] unsafe extern
                        "C" fn _post_return_open(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_open::<$ty > (arg0) } }
                        #[unsafe (export_name = "thoth:plugin/file-loader@0.1.0#get")]
                        unsafe extern "C" fn export_get(arg0 : i64,) -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_get_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/file-loader@0.1.0#get")] unsafe extern
                        "C" fn _post_return_get(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "thoth:plugin/file-loader@0.1.0#raw-bytes")] unsafe extern "C" fn
                        export_raw_bytes(arg0 : i64,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_raw_bytes_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/file-loader@0.1.0#raw-bytes")] unsafe
                        extern "C" fn _post_return_raw_bytes(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_raw_bytes::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_file_loader_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 16 + 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 16
                        + 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// file-viewer — implement when capability = file-viewer
            ///
            /// Lets a plugin control how its records are *rendered* inside the viewer
            /// panel. Without this capability the host falls back to the default JSON
            /// tree renderer.
            ///
            /// Because WASM cannot call egui directly, the plugin returns a lightweight
            /// render-node tree (think virtual DOM). The host walks the tree and draws
            /// it with egui.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod file_viewer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                /// How the plugin wants its data displayed.
                ///
                /// table  — host renders a styled table using column-headers() and the raw
                ///          JSON values from file-loader.get(). render-record() is never
                ///          called. This is the simplest option: the plugin only needs to
                ///          declare headers and the host takes care of the rest.
                ///
                /// custom — host calls render-record() for every visible row and draws
                ///          the returned RenderNode tree. Use this when you need badges,
                ///          colours, links, nested tables, or any non-trivial cell content.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum DisplayMode {
                    Table,
                    Custom,
                }
                impl ::core::fmt::Debug for DisplayMode {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            DisplayMode::Table => {
                                f.debug_tuple("DisplayMode::Table").finish()
                            }
                            DisplayMode::Custom => {
                                f.debug_tuple("DisplayMode::Custom").finish()
                            }
                        }
                    }
                }
                impl DisplayMode {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> DisplayMode {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => DisplayMode::Table,
                            1 => DisplayMode::Custom,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// A node in the render tree.
                /// Recursive types are not allowed in WIT, so children are encoded as
                /// a JSON string following the RenderNode schema below.
                /// Schema (recursive):
                ///   { "type": "text",       "value": "hello" }
                ///   { "type": "bold",       "child": <RenderNode> }
                ///   { "type": "italic",     "child": <RenderNode> }
                ///   { "type": "colored",    "color": "#ff6b6b", "child": <RenderNode> }
                ///   { "type": "badge",      "label": "WARN", "color": "#fbca04" }
                ///   { "type": "link",       "label": "docs", "url": "https://..." }
                ///   { "type": "row",        "children": [<RenderNode>, ...] }
                ///   { "type": "column",     "children": [<RenderNode>, ...] }
                ///   { "type": "key-value",  "key": "id",  "value": <RenderNode> }
                ///   { "type": "collapsible","label": "...", "children": [<RenderNode>, ...] }
                ///   { "type": "table",      "headers": ["col1", ...], "rows": [[<RenderNode>, ...], ...] }
                ///   { "type": "json-tree",  "value": <any JSON value> }
                #[derive(Clone)]
                pub struct RenderOutput {
                    /// JSON-encoded RenderNode tree (see schema above)
                    pub node_json: _rt::String,
                    /// Optional: height hint in logical pixels. 0 = auto.
                    pub height_hint: u32,
                }
                impl ::core::fmt::Debug for RenderOutput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("RenderOutput")
                            .field("node-json", &self.node_json)
                            .field("height-hint", &self.height_hint)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_preferred_display_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::preferred_display();
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_render_record_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::render_record(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let RenderOutput {
                                node_json: node_json3,
                                height_hint: height_hint3,
                            } = e;
                            let vec4 = (node_json3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(height_hint3);
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code5,
                                message: message5,
                            } = e;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code5);
                            let vec6 = (message5.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_render_record<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_column_headers_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::column_headers();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Some(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = e;
                            let len3 = vec3.len();
                            let layout3 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result3 = if layout3.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout3).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout3);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec3.into_iter().enumerate() {
                                let base = result3
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec2 = (e.into_bytes()).into_boxed_slice();
                                    let ptr2 = vec2.as_ptr().cast::<u8>();
                                    let len2 = vec2.len();
                                    ::core::mem::forget(vec2);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len2;
                                    *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                                }
                            }
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result3;
                        }
                        None => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_column_headers<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base5 = l1;
                            let len5 = l2;
                            for i in 0..len5 {
                                let base = base5
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = *base.add(0).cast::<*mut u8>();
                                    let l4 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l3, l4, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base5,
                                len5 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                    }
                }
                pub trait Guest {
                    /// Declare how this plugin's data should be displayed.
                    /// Called once after open(). Defaults to `table` if not implemented.
                    fn preferred_display() -> DisplayMode;
                    /// Given a single record as a JSON string (as returned by file-loader's
                    /// get()), return a render tree for the host to draw.
                    fn render_record(
                        record_json: _rt::String,
                    ) -> Result<RenderOutput, PluginError>;
                    /// Optional custom column headers for the table view.
                    /// Return `none` to use the keys from the first record as headers.
                    fn column_headers() -> Option<_rt::Vec<_rt::String>>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_file_viewer_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/file-viewer@0.1.0#preferred-display")] unsafe
                        extern "C" fn export_preferred_display() -> i32 { unsafe {
                        $($path_to_types)*:: _export_preferred_display_cabi::<$ty > () }
                        } #[unsafe (export_name =
                        "thoth:plugin/file-viewer@0.1.0#render-record")] unsafe extern
                        "C" fn export_render_record(arg0 : * mut u8, arg1 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_render_record_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_thoth:plugin/file-viewer@0.1.0#render-record")] unsafe
                        extern "C" fn _post_return_render_record(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_render_record::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "thoth:plugin/file-viewer@0.1.0#column-headers")] unsafe extern
                        "C" fn export_column_headers() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_column_headers_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/file-viewer@0.1.0#column-headers")]
                        unsafe extern "C" fn _post_return_column_headers(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_column_headers::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_file_viewer_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// plugin-meta — required by every plugin
            ///
            /// Maps from src/wit/mod.rs `Plugin` struct (as the return type of get-info).
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_meta {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginInfo = super::super::super::super::thoth::plugin::types::PluginInfo;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_info_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_info();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::thoth::plugin::types::PluginInfo {
                        id: id2,
                        name: name2,
                        version: version2,
                        description: description2,
                        capabilities: capabilities2,
                        author: author2,
                        homepage: homepage2,
                        icon: icon2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (name2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = (version2.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (description2.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = capabilities2;
                    let len7 = vec7.len();
                    let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec7.len() * 1,
                        1,
                    );
                    let result7 = if layout7.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout7);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec7.into_iter().enumerate() {
                        let base = result7.add(i * 1);
                        {
                            *base.add(0).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    }
                    *ptr1.add(9 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr1
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result7;
                    match author2 {
                        Some(e) => {
                            *ptr1
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec8 = (e.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr1
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr1
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match homepage2 {
                        Some(e) => {
                            *ptr1
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec9 = (e.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *ptr1
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *ptr1
                                .add(14 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match icon2 {
                        Some(e) => {
                            *ptr1
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec10 = (e.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *ptr1
                                .add(18 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr1
                                .add(17 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_info<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                    let l6 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l6, l7, 1);
                    let l8 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l9 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base10 = l8;
                    let len10 = l9;
                    _rt::cabi_dealloc(base10, len10 * 1, 1);
                    let l11 = i32::from(
                        *arg0.add(10 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l11 {
                        0 => {}
                        _ => {
                            let l12 = *arg0
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                    }
                    let l14 = i32::from(
                        *arg0.add(13 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l14 {
                        0 => {}
                        _ => {
                            let l15 = *arg0
                                .add(14 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *arg0
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l15, l16, 1);
                        }
                    }
                    let l17 = i32::from(
                        *arg0.add(16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l17 {
                        0 => {}
                        _ => {
                            let l18 = *arg0
                                .add(17 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l19 = *arg0
                                .add(18 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l18, l19, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Return static metadata about this plugin.
                    /// Called once by the host immediately after instantiation.
                    fn get_info() -> PluginInfo;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_meta_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-meta@0.1.0#get-info")] unsafe extern "C" fn
                        export_get_info() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_info_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/plugin-meta@0.1.0#get-info")] unsafe
                        extern "C" fn _post_return_get_info(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get_info::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_meta_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 19 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 19
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// plugin-lifecycle — required by every plugin
            ///
            /// Maps directly from src/wit/mod.rs `PluginLifeCycle` trait.
            /// Note: WIT uses kebab-case, Rust uses snake_case — toolchains handle the
            /// conversion automatically.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_lifecycle {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_load_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::on_load(_rt::string_lift(bytes0));
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_close_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::on_close();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_setting_change_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::on_setting_change(_rt::string_lift(bytes0));
                }
                pub trait Guest {
                    /// Called by the host after the plugin is fully loaded and registered.
                    /// Use this to initialise any internal state.
                    /// Setting is passed in setting-data format, eg: "[{key: "url", value: "https://..."}, ...]"
                    fn on_load(setting: _rt::String) -> ();
                    /// Called by the host before the plugin is unloaded (app shutdown or
                    /// the user disabling the plugin via Settings → Plugins).
                    /// Release any held resources (open file handles, connections, etc.).
                    fn on_close() -> ();
                    /// Called by the host when the user saves settings in the plugin settings
                    fn on_setting_change(setting: _rt::String) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_lifecycle_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-load")] unsafe extern "C"
                        fn export_on_load(arg0 : * mut u8, arg1 : usize,) { unsafe {
                        $($path_to_types)*:: _export_on_load_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-close")] unsafe extern
                        "C" fn export_on_close() { unsafe { $($path_to_types)*::
                        _export_on_close_cabi::<$ty > () } } #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-setting-change")] unsafe
                        extern "C" fn export_on_setting_change(arg0 : * mut u8, arg1 :
                        usize,) { unsafe { $($path_to_types)*::
                        _export_on_setting_change_cabi::<$ty > (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_lifecycle_0_1_0_cabi;
            }
            /// ---------------------------------------------------------------------------
            /// Worlds — plugin authors implement one of these
            ///
            /// A world declares exactly which interfaces a plugin exports. Pick the
            /// world that matches your plugin's capabilities. If you implement multiple
            /// capabilities, implement the combined world or compose component binaries.
            /// ---------------------------------------------------------------------------
            /// ---------------------------------------------------------------------------
            /// plugin-settings — implement on every plugin (trivial no-op is fine)
            ///
            /// Lets a plugin own its settings UI. The host calls render-settings() once
            /// with the persisted key/value pairs; the plugin returns a UiNode tree.
            /// Events from the UI (text-input changes, button clicks, etc.) are forwarded
            /// back via handle-setting-event(). On Save the host calls get-settings() to
            /// read the current values for persistence, and calls apply-settings() on the
            /// next load so the plugin can restore its state.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_settings {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                #[derive(Clone)]
                pub struct SettingsOutput {
                    /// JSON-encoded UiNode tree (same DSL as ui-component).
                    pub node_json: _rt::String,
                    /// Height hint in logical pixels; 0 = auto.
                    pub height_hint: u32,
                }
                impl ::core::fmt::Debug for SettingsOutput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SettingsOutput")
                            .field("node-json", &self.node_json)
                            .field("height-hint", &self.height_hint)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_render_settings_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::render_settings();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let SettingsOutput {
                                node_json: node_json2,
                                height_hint: height_hint2,
                            } = e;
                            let vec3 = (node_json2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(height_hint2);
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code4,
                                message: message4,
                            } = e;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code4);
                            let vec5 = (message4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_render_settings<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Render the settings UI. Called once when the user opens the settings for this plugin.
                    fn render_settings() -> Result<SettingsOutput, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_settings_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-settings@0.1.0#render-settings")] unsafe
                        extern "C" fn export_render_settings() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_render_settings_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/plugin-settings@0.1.0#render-settings")]
                        unsafe extern "C" fn _post_return_render_settings(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_render_settings::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_settings_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_file_viewer_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::thoth::plugin::file_loader::__export_thoth_plugin_file_loader_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::file_loader);
        $($path_to_types_root)*::
        exports::thoth::plugin::file_viewer::__export_thoth_plugin_file_viewer_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::file_viewer);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_meta::__export_thoth_plugin_plugin_meta_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::plugin_meta);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_lifecycle::__export_thoth_plugin_plugin_lifecycle_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::thoth::plugin::plugin_lifecycle); $($path_to_types_root)*::
        exports::thoth::plugin::plugin_settings::__export_thoth_plugin_plugin_settings_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::plugin_settings);
    };
}
#[doc(inline)]
pub(crate) use __export_file_viewer_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:thoth:plugin@0.1.0:file-viewer-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1260] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe3\x08\x01A\x02\x01\
A\x0e\x01B\x0a\x01m\x06\x0bfile-loader\x0bfile-viewer\x0bdata-source\x08exporter\
\x0fsearch-provider\x10new-ui-component\x04\0\x0acapability\x03\0\0\x01p\x01\x01\
ks\x01r\x08\x02ids\x04names\x07versions\x0bdescriptions\x0ccapabilities\x02\x06a\
uthor\x03\x08homepage\x03\x04icon\x03\x04\0\x0bplugin-info\x03\0\x04\x01r\x02\x04\
codey\x07messages\x04\0\x0cplugin-error\x03\0\x06\x01r\x02\x03keys\x05values\x04\
\0\x0csetting-data\x03\0\x08\x03\0\x18thoth:plugin/types@0.1.0\x05\0\x02\x03\0\0\
\x0cplugin-error\x01B\x0f\x02\x03\x02\x01\x01\x04\0\x0cplugin-error\x03\0\0\x01p\
s\x01@\0\0\x02\x04\0\x14supported-extensions\x01\x03\x01j\x01w\x01\x01\x01@\x01\x04\
paths\0\x04\x04\0\x04open\x01\x05\x01j\x01s\x01\x01\x01@\x01\x03idxw\0\x06\x04\0\
\x03get\x01\x07\x01p}\x01j\x01\x08\x01\x01\x01@\x01\x03idxw\0\x09\x04\0\x09raw-b\
ytes\x01\x0a\x04\0\x1ethoth:plugin/file-loader@0.1.0\x05\x02\x01B\x0f\x02\x03\x02\
\x01\x01\x04\0\x0cplugin-error\x03\0\0\x01m\x02\x05table\x06custom\x04\0\x0cdisp\
lay-mode\x03\0\x02\x01r\x02\x09node-jsons\x0bheight-hinty\x04\0\x0drender-output\
\x03\0\x04\x01@\0\0\x03\x04\0\x11preferred-display\x01\x06\x01j\x01\x05\x01\x01\x01\
@\x01\x0brecord-jsons\0\x07\x04\0\x0drender-record\x01\x08\x01ps\x01k\x09\x01@\0\
\0\x0a\x04\0\x0ecolumn-headers\x01\x0b\x04\0\x1ethoth:plugin/file-viewer@0.1.0\x05\
\x03\x02\x03\0\0\x0bplugin-info\x01B\x04\x02\x03\x02\x01\x04\x04\0\x0bplugin-inf\
o\x03\0\0\x01@\0\0\x01\x04\0\x08get-info\x01\x02\x04\0\x1ethoth:plugin/plugin-me\
ta@0.1.0\x05\x05\x01B\x05\x01@\x01\x07settings\x01\0\x04\0\x07on-load\x01\0\x01@\
\0\x01\0\x04\0\x08on-close\x01\x01\x04\0\x11on-setting-change\x01\0\x04\0#thoth:\
plugin/plugin-lifecycle@0.1.0\x05\x06\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0cplug\
in-error\x03\0\0\x01r\x02\x09node-jsons\x0bheight-hinty\x04\0\x0fsettings-output\
\x03\0\x02\x01j\x01\x03\x01\x01\x01@\0\0\x04\x04\0\x0frender-settings\x01\x05\x04\
\0\"thoth:plugin/plugin-settings@0.1.0\x05\x07\x04\0%thoth:plugin/file-viewer-pl\
ugin@0.1.0\x04\0\x0b\x18\x01\0\x12file-viewer-plugin\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
