pub const KEYWORDS: [&str; 95] = [
    // Data Manipulation (DML)
    "SELECT",
    "FROM",
    "WHERE",
    "INSERT",
    "UPDATE",
    "DELETE",
    "INTO",
    "VALUES",
    "SET",
    "JOIN",
    "LEFT",
    "RIGHT",
    "INNER",
    "FULL",
    "OUTER",
    "CROSS",
    "ON",
    "USING",
    "GROUP",
    "BY",
    "ORDER",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "FETCH",
    "FIRST",
    "NEXT",
    "ROWS",
    "ONLY",
    "UNION",
    "INTERSECT",
    "EXCEPT",
    "ALL",
    "DISTINCT",
    // Data Definition (DDL)
    "CREATE",
    "ALTER",
    "DROP",
    "TABLE",
    "DATABASE",
    "SCHEMA",
    "VIEW",
    "INDEX",
    "SEQUENCE",
    "TRIGGER",
    "FUNCTION",
    "PROCEDURE",
    "TYPE",
    "EXTENSION",
    "OWNER",
    "TO",
    "COLUMN",
    "CONSTRAINT",
    "PRIMARY",
    "KEY",
    "FOREIGN",
    "REFERENCES",
    "UNIQUE",
    "CHECK",
    "DEFAULT",
    "NOT",
    "NULL",
    "RENAME",
    "ADD",
    "REPLACE",
    // Control & Clauses
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "WITH",
    "RECURSIVE",
    "AS",
    "WINDOW",
    "OVER",
    "PARTITION",
    "ROWS",
    "RANGE",
    "BETWEEN",
    "UNBOUNDED",
    "PRECEDING",
    "FOLLOWING",
    "RETURNING",
    "ON",
    "CONFLICT",
    "DO",
    "NOTHING", // Postgres Upsert
    "VACUUM",
    "ANALYZE",
    "EXPLAIN",
    "SHOW",
    "LISTEN",
    "NOTIFY",
    "BEGIN",
    "COMMIT",
    "ROLLBACK",
];

// 2. Built-in PostgreSQL Data Types
pub const TYPES: [&str; 44] = [
    // Numeric
    "SMALLINT",
    "INT",
    "INTEGER",
    "BIGINT",
    "DECIMAL",
    "NUMERIC",
    "REAL",
    "DOUBLE",
    "PRECISION",
    "SERIAL",
    "BIGSERIAL",
    // Character / Text
    "VARCHAR",
    "CHARACTER",
    "VARYING",
    "CHAR",
    "TEXT",
    // Binary / UUID / JSON
    "BYTEA",
    "UUID",
    "JSON",
    "JSONB",
    "XML",
    // Date / Time
    "DATE",
    "TIME",
    "TIMESTAMP",
    "TIMESTAMPTZ",
    "INTERVAL",
    "WITHOUT",
    "WITH",
    "ZONE",
    // Boolean & Network
    "BOOLEAN",
    "BOOL",
    "CIDR",
    "INET",
    "MACADDR",
    "MACADDR8",
    // Geometric & Text Search
    "POINT",
    "LINE",
    "LSEG",
    "BOX",
    "PATH",
    "POLYGON",
    "CIRCLE",
    "TSVECTOR",
    "TSQUERY",
];

// 3. Operators, Logical Words, and Built-in Functions
pub const SPECIAL: [&str; 36] = [
    // Logical & Operators
    "AND",
    "OR",
    "NOT",
    "IN",
    "ANY",
    "SOME",
    "ALL",
    "EXISTS",
    "BETWEEN",
    "LIKE",
    "ILIKE",
    "SIMILAR",
    "IS",
    "TRUE",
    "FALSE",
    // Common Aggregate / Window Functions
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "COALESCE",
    "NULLIF",
    "GREATEST",
    "LEAST",
    "ROW_NUMBER",
    "RANK",
    "DENSE_RANK",
    "LAG",
    "LEAD",
    "FIRST_VALUE",
    "LAST_VALUE",
    // JSONB Functions / Operators
    "JSONB_BUILD_OBJECT",
    "JSONB_BUILD_ARRAY",
    "JSONB_AGG",
    "JSONB_TO_RECORD",
    "JSON_EACH",
];
