// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod thoth {
    pub mod plugin {
        /// ---------------------------------------------------------------------------
        /// Shared types — imported by every interface below
        /// ---------------------------------------------------------------------------
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Maps from src/wit/mod.rs `Capabilities` enum.
            /// Declare which of these your plugin implements in `plugin-info`.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Capability {
                FileLoader,
                FileViewer,
                DataSource,
                Exporter,
                SearchProvider,
                NewUiComponent,
                /// A dataset producer for the data bus (#113): the plugin exports
                /// data-producer.provide-dataset and opts in to being offered as a
                /// source in the consumer's picker.
                DataProducer,
                /// A dataset renderer for the data bus (#135): the plugin exports
                /// data-renderer.render and appears as an extra view format in a
                /// DataView (alongside table / json / raw).
                Renderer,
                /// Exposes commands through the optional plugin-cli interface.
                Cli,
            }
            impl ::core::fmt::Debug for Capability {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Capability::FileLoader => {
                            f.debug_tuple("Capability::FileLoader").finish()
                        }
                        Capability::FileViewer => {
                            f.debug_tuple("Capability::FileViewer").finish()
                        }
                        Capability::DataSource => {
                            f.debug_tuple("Capability::DataSource").finish()
                        }
                        Capability::Exporter => {
                            f.debug_tuple("Capability::Exporter").finish()
                        }
                        Capability::SearchProvider => {
                            f.debug_tuple("Capability::SearchProvider").finish()
                        }
                        Capability::NewUiComponent => {
                            f.debug_tuple("Capability::NewUiComponent").finish()
                        }
                        Capability::DataProducer => {
                            f.debug_tuple("Capability::DataProducer").finish()
                        }
                        Capability::Renderer => {
                            f.debug_tuple("Capability::Renderer").finish()
                        }
                        Capability::Cli => f.debug_tuple("Capability::Cli").finish(),
                    }
                }
            }
            impl Capability {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Capability {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Capability::FileLoader,
                        1 => Capability::FileViewer,
                        2 => Capability::DataSource,
                        3 => Capability::Exporter,
                        4 => Capability::SearchProvider,
                        5 => Capability::NewUiComponent,
                        6 => Capability::DataProducer,
                        7 => Capability::Renderer,
                        8 => Capability::Cli,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Maps from src/wit/mod.rs `Plugin` struct.
            /// `location` is intentionally absent here — it is set by the host at
            /// discovery time (the path where the .wasm file lives) and is not
            /// something the plugin itself knows or declares.
            #[derive(Clone)]
            pub struct PluginInfo {
                pub id: _rt::String,
                /// reverse-domain unique id, e.g. "com.example.csv-loader"
                pub name: _rt::String,
                /// human-readable, e.g. "CSV Loader"
                pub version: _rt::String,
                /// semver string, e.g. "0.2.1"
                pub description: _rt::String,
                pub capabilities: _rt::Vec<Capability>,
                pub author: Option<_rt::String>,
                pub homepage: Option<_rt::String>,
                /// Sidebar icon glyph. Use a phosphor icon Unicode character (e.g. "\u{E28C}").
                /// Falls back to a generic database icon when absent.
                pub icon: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for PluginInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginInfo")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("description", &self.description)
                        .field("capabilities", &self.capabilities)
                        .field("author", &self.author)
                        .field("homepage", &self.homepage)
                        .field("icon", &self.icon)
                        .finish()
                }
            }
            /// Unified error type used across all interfaces.
            #[derive(Clone)]
            pub struct PluginError {
                pub code: u32,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginError")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod thoth {
        pub mod plugin {
            /// ---------------------------------------------------------------------------
            /// exporter — implement when capability = exporter
            ///
            /// Adds a new export format or destination to the File → Export menu.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod exporter {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                /// A user-configurable option shown in the export dialog.
                #[derive(Clone)]
                pub struct ExportOption {
                    pub key: _rt::String,
                    /// internal key
                    pub label: _rt::String,
                    /// shown in the UI
                    pub default_value: _rt::String,
                    /// "text" | "bool" | "select" — drives the input widget type
                    pub input_type: _rt::String,
                    /// Non-empty only when input-type = "select"
                    pub choices: _rt::Vec<_rt::String>,
                }
                impl ::core::fmt::Debug for ExportOption {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExportOption")
                            .field("key", &self.key)
                            .field("label", &self.label)
                            .field("default-value", &self.default_value)
                            .field("input-type", &self.input_type)
                            .field("choices", &self.choices)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_name_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::name();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_name<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_output_extension_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::output_extension();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_output_extension<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_available_options_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::available_options();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec9 = result0;
                    let len9 = vec9.len();
                    let layout9 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec9.len() * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result9 = if layout9.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout9).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout9);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec9.into_iter().enumerate() {
                        let base = result9
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let ExportOption {
                                key: key2,
                                label: label2,
                                default_value: default_value2,
                                input_type: input_type2,
                                choices: choices2,
                            } = e;
                            let vec3 = (key2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (label2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (default_value2.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = (input_type2.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *base
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                            let vec8 = choices2;
                            let len8 = vec8.len();
                            let layout8 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec8.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result8 = if layout8.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout8).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout8);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec8.into_iter().enumerate() {
                                let base = result8
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec7 = (e.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *base.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                                }
                            }
                            *base
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *base
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result8;
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
                    *ptr1.add(0).cast::<*mut u8>() = result9;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_available_options<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base15 = l0;
                    let len15 = l1;
                    for i in 0..len15 {
                        let base = base15
                            .add(i * (10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                            let l6 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                            let l8 = *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *base
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                            let l10 = *base
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l11 = *base
                                .add(9 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base14 = l10;
                            let len14 = l11;
                            for i in 0..len14 {
                                let base = base14
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l12 = *base.add(0).cast::<*mut u8>();
                                    let l13 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l12, l13, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base14,
                                len14 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                    }
                    _rt::cabi_dealloc(
                        base15,
                        len15 * (10 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let base7 = arg2;
                    let len7 = arg3;
                    let mut result7 = _rt::Vec::with_capacity(len7);
                    for i in 0..len7 {
                        let base = base7
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e7 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            (_rt::string_lift(bytes3), _rt::string_lift(bytes6))
                        };
                        result7.push(e7);
                    }
                    _rt::cabi_dealloc(
                        base7,
                        len7 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result8 = T::run(_rt::string_lift(bytes0), result7);
                    let ptr9 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result8 {
                        Ok(e) => {
                            *ptr9.add(0).cast::<u8>() = (0i32) as u8;
                            let vec10 = (e).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *ptr9
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr9
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                        }
                        Err(e) => {
                            *ptr9.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code11,
                                message: message11,
                            } = e;
                            *ptr9
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code11);
                            let vec12 = (message11.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *ptr9
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr9
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                        }
                    };
                    ptr9
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Human-readable name for this format, e.g. "CSV Export"
                    fn name() -> _rt::String;
                    /// File extension for the output without the dot, e.g. "csv"
                    fn output_extension() -> _rt::String;
                    /// Options the host should display in the export dialog.
                    fn available_options() -> _rt::Vec<ExportOption>;
                    /// Perform the export.
                    /// `records-json` is the host-owned dataset as a JSON object
                    /// `{ "columns": ["c1", ...], "rows": [["v1", ...], ...] }` — column order is
                    /// preserved and every cell is a string (v1 dataset shape). The host reads
                    /// its single owned copy and passes it here; the plugin never touches the bus.
                    /// `options` is a flat key/value list of the user's chosen option values.
                    /// Returns raw file bytes the host writes to disk.
                    fn run(
                        records_json: _rt::String,
                        options: _rt::Vec<(_rt::String, _rt::String)>,
                    ) -> Result<_rt::Vec<u8>, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_exporter_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/exporter@0.1.0#name")] unsafe extern "C" fn
                        export_name() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_name_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/exporter@0.1.0#name")] unsafe extern "C"
                        fn _post_return_name(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_name::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "thoth:plugin/exporter@0.1.0#output-extension")] unsafe extern
                        "C" fn export_output_extension() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_output_extension_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/exporter@0.1.0#output-extension")] unsafe
                        extern "C" fn _post_return_output_extension(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_output_extension::<$ty > (arg0) } } #[unsafe
                        (export_name = "thoth:plugin/exporter@0.1.0#available-options")]
                        unsafe extern "C" fn export_available_options() -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_available_options_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_thoth:plugin/exporter@0.1.0#available-options")]
                        unsafe extern "C" fn _post_return_available_options(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_available_options::<$ty > (arg0) } } #[unsafe
                        (export_name = "thoth:plugin/exporter@0.1.0#run")] unsafe extern
                        "C" fn export_run(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_run_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe
                        (export_name = "cabi_post_thoth:plugin/exporter@0.1.0#run")]
                        unsafe extern "C" fn _post_return_run(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_run::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_exporter_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// Worlds — plugin authors implement one of these
            ///
            /// A world declares exactly which interfaces a plugin exports. Pick the
            /// world that matches your plugin's capabilities. If you implement multiple
            /// capabilities, implement the combined world or compose component binaries.
            /// ---------------------------------------------------------------------------
            /// ---------------------------------------------------------------------------
            /// plugin-settings — implement on every plugin (trivial no-op is fine)
            ///
            /// Lets a plugin own its settings UI. The host calls render-settings() once
            /// with the persisted key/value pairs; the plugin returns a UiNode tree.
            /// Events from the UI (text-input changes, button clicks, etc.) are forwarded
            /// back via handle-setting-event(). On Save the host calls get-settings() to
            /// read the current values for persistence, and calls apply-settings() on the
            /// next load so the plugin can restore its state.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_settings {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                #[derive(Clone)]
                pub struct SettingsOutput {
                    /// JSON-encoded UiNode tree (same DSL as ui-component).
                    pub node_json: _rt::String,
                    /// Height hint in logical pixels; 0 = auto.
                    pub height_hint: u32,
                }
                impl ::core::fmt::Debug for SettingsOutput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SettingsOutput")
                            .field("node-json", &self.node_json)
                            .field("height-hint", &self.height_hint)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_render_settings_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::render_settings();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let SettingsOutput {
                                node_json: node_json2,
                                height_hint: height_hint2,
                            } = e;
                            let vec3 = (node_json2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(height_hint2);
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code4,
                                message: message4,
                            } = e;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code4);
                            let vec5 = (message4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_render_settings<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Render the settings UI. Called once when the user opens the settings for this plugin.
                    fn render_settings() -> Result<SettingsOutput, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_settings_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-settings@0.1.0#render-settings")] unsafe
                        extern "C" fn export_render_settings() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_render_settings_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/plugin-settings@0.1.0#render-settings")]
                        unsafe extern "C" fn _post_return_render_settings(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_render_settings::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_settings_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// plugin-meta — required by every plugin
            ///
            /// Maps from src/wit/mod.rs `Plugin` struct (as the return type of get-info).
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_meta {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginInfo = super::super::super::super::thoth::plugin::types::PluginInfo;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_info_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_info();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::thoth::plugin::types::PluginInfo {
                        id: id2,
                        name: name2,
                        version: version2,
                        description: description2,
                        capabilities: capabilities2,
                        author: author2,
                        homepage: homepage2,
                        icon: icon2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (name2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = (version2.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (description2.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = capabilities2;
                    let len7 = vec7.len();
                    let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec7.len() * 1,
                        1,
                    );
                    let result7 = if layout7.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout7);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec7.into_iter().enumerate() {
                        let base = result7.add(i * 1);
                        {
                            *base.add(0).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    }
                    *ptr1.add(9 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr1
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result7;
                    match author2 {
                        Some(e) => {
                            *ptr1
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec8 = (e.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr1
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr1
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match homepage2 {
                        Some(e) => {
                            *ptr1
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec9 = (e.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *ptr1
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *ptr1
                                .add(14 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match icon2 {
                        Some(e) => {
                            *ptr1
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec10 = (e.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *ptr1
                                .add(18 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr1
                                .add(17 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_info<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                    let l6 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l6, l7, 1);
                    let l8 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l9 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base10 = l8;
                    let len10 = l9;
                    _rt::cabi_dealloc(base10, len10 * 1, 1);
                    let l11 = i32::from(
                        *arg0.add(10 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l11 {
                        0 => {}
                        _ => {
                            let l12 = *arg0
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                    }
                    let l14 = i32::from(
                        *arg0.add(13 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l14 {
                        0 => {}
                        _ => {
                            let l15 = *arg0
                                .add(14 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *arg0
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l15, l16, 1);
                        }
                    }
                    let l17 = i32::from(
                        *arg0.add(16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l17 {
                        0 => {}
                        _ => {
                            let l18 = *arg0
                                .add(17 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l19 = *arg0
                                .add(18 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l18, l19, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Return static metadata about this plugin.
                    /// Called once by the host immediately after instantiation.
                    fn get_info() -> PluginInfo;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_meta_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-meta@0.1.0#get-info")] unsafe extern "C" fn
                        export_get_info() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_info_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/plugin-meta@0.1.0#get-info")] unsafe
                        extern "C" fn _post_return_get_info(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get_info::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_meta_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 19 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 19
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// plugin-lifecycle — required by every plugin
            ///
            /// Maps directly from src/wit/mod.rs `PluginLifeCycle` trait.
            /// Note: WIT uses kebab-case, Rust uses snake_case — toolchains handle the
            /// conversion automatically.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_lifecycle {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_load_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::on_load(_rt::string_lift(bytes0));
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_close_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::on_close();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_setting_change_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::on_setting_change(_rt::string_lift(bytes0));
                }
                pub trait Guest {
                    /// Called by the host after the plugin is fully loaded and registered.
                    /// Use this to initialise any internal state.
                    /// Setting is passed in setting-data format, eg: "[{key: "url", value: "https://..."}, ...]"
                    fn on_load(setting: _rt::String) -> ();
                    /// Called by the host before the plugin is unloaded (app shutdown or
                    /// the user disabling the plugin via Settings → Plugins).
                    /// Release any held resources (open file handles, connections, etc.).
                    fn on_close() -> ();
                    /// Called by the host when the user saves settings in the plugin settings
                    fn on_setting_change(setting: _rt::String) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_lifecycle_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-load")] unsafe extern "C"
                        fn export_on_load(arg0 : * mut u8, arg1 : usize,) { unsafe {
                        $($path_to_types)*:: _export_on_load_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-close")] unsafe extern
                        "C" fn export_on_close() { unsafe { $($path_to_types)*::
                        _export_on_close_cabi::<$ty > () } } #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-setting-change")] unsafe
                        extern "C" fn export_on_setting_change(arg0 : * mut u8, arg1 :
                        usize,) { unsafe { $($path_to_types)*::
                        _export_on_setting_change_cabi::<$ty > (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_lifecycle_0_1_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_exporter_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::thoth::plugin::exporter::__export_thoth_plugin_exporter_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::exporter);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_settings::__export_thoth_plugin_plugin_settings_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::plugin_settings);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_meta::__export_thoth_plugin_plugin_meta_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::plugin_meta);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_lifecycle::__export_thoth_plugin_plugin_lifecycle_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::thoth::plugin::plugin_lifecycle);
    };
}
#[doc(inline)]
pub(crate) use __export_exporter_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:thoth:plugin@0.1.0:exporter-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1113] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd3\x07\x01A\x02\x01\
A\x0c\x01B\x0a\x01m\x09\x0bfile-loader\x0bfile-viewer\x0bdata-source\x08exporter\
\x0fsearch-provider\x10new-ui-component\x0ddata-producer\x08renderer\x03cli\x04\0\
\x0acapability\x03\0\0\x01p\x01\x01ks\x01r\x08\x02ids\x04names\x07versions\x0bde\
scriptions\x0ccapabilities\x02\x06author\x03\x08homepage\x03\x04icon\x03\x04\0\x0b\
plugin-info\x03\0\x04\x01r\x02\x04codey\x07messages\x04\0\x0cplugin-error\x03\0\x06\
\x01r\x02\x03keys\x05values\x04\0\x0csetting-data\x03\0\x08\x03\0\x18thoth:plugi\
n/types@0.1.0\x05\0\x02\x03\0\0\x0cplugin-error\x01B\x11\x02\x03\x02\x01\x01\x04\
\0\x0cplugin-error\x03\0\0\x01ps\x01r\x05\x03keys\x05labels\x0ddefault-values\x0a\
input-types\x07choices\x02\x04\0\x0dexport-option\x03\0\x03\x01@\0\0s\x04\0\x04n\
ame\x01\x05\x04\0\x10output-extension\x01\x05\x01p\x04\x01@\0\0\x06\x04\0\x11ava\
ilable-options\x01\x07\x01o\x02ss\x01p\x08\x01p}\x01j\x01\x0a\x01\x01\x01@\x02\x0c\
records-jsons\x07options\x09\0\x0b\x04\0\x03run\x01\x0c\x04\0\x1bthoth:plugin/ex\
porter@0.1.0\x05\x02\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0cplugin-error\x03\0\0\x01\
r\x02\x09node-jsons\x0bheight-hinty\x04\0\x0fsettings-output\x03\0\x02\x01j\x01\x03\
\x01\x01\x01@\0\0\x04\x04\0\x0frender-settings\x01\x05\x04\0\"thoth:plugin/plugi\
n-settings@0.1.0\x05\x03\x02\x03\0\0\x0bplugin-info\x01B\x04\x02\x03\x02\x01\x04\
\x04\0\x0bplugin-info\x03\0\0\x01@\0\0\x01\x04\0\x08get-info\x01\x02\x04\0\x1eth\
oth:plugin/plugin-meta@0.1.0\x05\x05\x01B\x05\x01@\x01\x07settings\x01\0\x04\0\x07\
on-load\x01\0\x01@\0\x01\0\x04\0\x08on-close\x01\x01\x04\0\x11on-setting-change\x01\
\0\x04\0#thoth:plugin/plugin-lifecycle@0.1.0\x05\x06\x04\0\"thoth:plugin/exporte\
r-plugin@0.1.0\x04\0\x0b\x15\x01\0\x0fexporter-plugin\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
