// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod thoth {
    pub mod plugin {
        /// ---------------------------------------------------------------------------
        /// Shared types — imported by every interface below
        /// ---------------------------------------------------------------------------
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Maps from src/wit/mod.rs `Capabilities` enum.
            /// Declare which of these your plugin implements in `plugin-info`.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Capability {
                FileLoader,
                FileViewer,
                DataSource,
                Exporter,
                SearchProvider,
                NewUiComponent,
                /// A dataset producer for the data bus (#113): the plugin exports
                /// data-producer.provide-dataset and opts in to being offered as a
                /// source in the consumer's picker.
                DataProducer,
                /// A dataset renderer for the data bus (#135): the plugin exports
                /// data-renderer.render and appears as an extra view format in a
                /// DataView (alongside table / json / raw).
                Renderer,
            }
            impl ::core::fmt::Debug for Capability {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Capability::FileLoader => {
                            f.debug_tuple("Capability::FileLoader").finish()
                        }
                        Capability::FileViewer => {
                            f.debug_tuple("Capability::FileViewer").finish()
                        }
                        Capability::DataSource => {
                            f.debug_tuple("Capability::DataSource").finish()
                        }
                        Capability::Exporter => {
                            f.debug_tuple("Capability::Exporter").finish()
                        }
                        Capability::SearchProvider => {
                            f.debug_tuple("Capability::SearchProvider").finish()
                        }
                        Capability::NewUiComponent => {
                            f.debug_tuple("Capability::NewUiComponent").finish()
                        }
                        Capability::DataProducer => {
                            f.debug_tuple("Capability::DataProducer").finish()
                        }
                        Capability::Renderer => {
                            f.debug_tuple("Capability::Renderer").finish()
                        }
                    }
                }
            }
            impl Capability {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Capability {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Capability::FileLoader,
                        1 => Capability::FileViewer,
                        2 => Capability::DataSource,
                        3 => Capability::Exporter,
                        4 => Capability::SearchProvider,
                        5 => Capability::NewUiComponent,
                        6 => Capability::DataProducer,
                        7 => Capability::Renderer,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Maps from src/wit/mod.rs `Plugin` struct.
            /// `location` is intentionally absent here — it is set by the host at
            /// discovery time (the path where the .wasm file lives) and is not
            /// something the plugin itself knows or declares.
            #[derive(Clone)]
            pub struct PluginInfo {
                pub id: _rt::String,
                /// reverse-domain unique id, e.g. "com.example.csv-loader"
                pub name: _rt::String,
                /// human-readable, e.g. "CSV Loader"
                pub version: _rt::String,
                /// semver string, e.g. "0.2.1"
                pub description: _rt::String,
                pub capabilities: _rt::Vec<Capability>,
                pub author: Option<_rt::String>,
                pub homepage: Option<_rt::String>,
                /// Sidebar icon glyph. Use a phosphor icon Unicode character (e.g. "\u{E28C}").
                /// Falls back to a generic database icon when absent.
                pub icon: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for PluginInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginInfo")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("description", &self.description)
                        .field("capabilities", &self.capabilities)
                        .field("author", &self.author)
                        .field("homepage", &self.homepage)
                        .field("icon", &self.icon)
                        .finish()
                }
            }
            /// Unified error type used across all interfaces.
            #[derive(Clone)]
            pub struct PluginError {
                pub code: u32,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginError")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod thoth {
        pub mod plugin {
            /// ---------------------------------------------------------------------------
            /// data-renderer — a plugin that presents a host-owned dataset in a novel way
            /// (#135). It appears as an extra view format in a DataView (alongside the
            /// built-in table / json / raw). The host reads its single owned copy, passes
            /// the rows here, and draws the RenderNode tree the plugin returns — the plugin
            /// only *describes* UI, exactly like the built-in components.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod data_renderer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_name_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::name();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_name<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_render_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::render(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code4,
                                message: message4,
                            } = e;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code4);
                            let vec5 = (message4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_render<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Short label for the view (shown in the DataView's view dropdown), e.g. "Cards".
                    fn name() -> _rt::String;
                    /// Render the dataset. `records-json` is the same shape the exporter gets —
                    /// `{ "columns": [...], "rows": [[...], ...] }` (order preserved, string
                    /// cells). Returns a serialized `RenderNode` tree (node-json) the host draws
                    /// inside the DataView.
                    fn render(
                        records_json: _rt::String,
                    ) -> Result<_rt::String, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_data_renderer_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/data-renderer@0.1.0#name")] unsafe extern "C" fn
                        export_name() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_name_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/data-renderer@0.1.0#name")] unsafe extern
                        "C" fn _post_return_name(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_name::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "thoth:plugin/data-renderer@0.1.0#render")] unsafe extern "C" fn
                        export_render(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_render_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/data-renderer@0.1.0#render")] unsafe
                        extern "C" fn _post_return_render(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_render::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_data_renderer_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// plugin-meta — required by every plugin
            ///
            /// Maps from src/wit/mod.rs `Plugin` struct (as the return type of get-info).
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_meta {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginInfo = super::super::super::super::thoth::plugin::types::PluginInfo;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_info_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_info();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::thoth::plugin::types::PluginInfo {
                        id: id2,
                        name: name2,
                        version: version2,
                        description: description2,
                        capabilities: capabilities2,
                        author: author2,
                        homepage: homepage2,
                        icon: icon2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (name2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = (version2.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (description2.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = capabilities2;
                    let len7 = vec7.len();
                    let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec7.len() * 1,
                        1,
                    );
                    let result7 = if layout7.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout7);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec7.into_iter().enumerate() {
                        let base = result7.add(i * 1);
                        {
                            *base.add(0).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    }
                    *ptr1.add(9 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr1
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result7;
                    match author2 {
                        Some(e) => {
                            *ptr1
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec8 = (e.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr1
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr1
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(10 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match homepage2 {
                        Some(e) => {
                            *ptr1
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec9 = (e.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *ptr1
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *ptr1
                                .add(14 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    match icon2 {
                        Some(e) => {
                            *ptr1
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (1i32) as u8;
                            let vec10 = (e.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *ptr1
                                .add(18 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr1
                                .add(17 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                        }
                        None => {
                            *ptr1
                                .add(16 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_info<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                    let l6 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l6, l7, 1);
                    let l8 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l9 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base10 = l8;
                    let len10 = l9;
                    _rt::cabi_dealloc(base10, len10 * 1, 1);
                    let l11 = i32::from(
                        *arg0.add(10 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l11 {
                        0 => {}
                        _ => {
                            let l12 = *arg0
                                .add(11 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l12, l13, 1);
                        }
                    }
                    let l14 = i32::from(
                        *arg0.add(13 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l14 {
                        0 => {}
                        _ => {
                            let l15 = *arg0
                                .add(14 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *arg0
                                .add(15 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l15, l16, 1);
                        }
                    }
                    let l17 = i32::from(
                        *arg0.add(16 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    match l17 {
                        0 => {}
                        _ => {
                            let l18 = *arg0
                                .add(17 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l19 = *arg0
                                .add(18 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l18, l19, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Return static metadata about this plugin.
                    /// Called once by the host immediately after instantiation.
                    fn get_info() -> PluginInfo;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_meta_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-meta@0.1.0#get-info")] unsafe extern "C" fn
                        export_get_info() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_info_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_thoth:plugin/plugin-meta@0.1.0#get-info")] unsafe
                        extern "C" fn _post_return_get_info(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get_info::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_meta_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 19 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 19
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// ---------------------------------------------------------------------------
            /// plugin-lifecycle — required by every plugin
            ///
            /// Maps directly from src/wit/mod.rs `PluginLifeCycle` trait.
            /// Note: WIT uses kebab-case, Rust uses snake_case — toolchains handle the
            /// conversion automatically.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_lifecycle {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_load_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::on_load(_rt::string_lift(bytes0));
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_close_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::on_close();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_setting_change_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::on_setting_change(_rt::string_lift(bytes0));
                }
                pub trait Guest {
                    /// Called by the host after the plugin is fully loaded and registered.
                    /// Use this to initialise any internal state.
                    /// Setting is passed in setting-data format, eg: "[{key: "url", value: "https://..."}, ...]"
                    fn on_load(setting: _rt::String) -> ();
                    /// Called by the host before the plugin is unloaded (app shutdown or
                    /// the user disabling the plugin via Settings → Plugins).
                    /// Release any held resources (open file handles, connections, etc.).
                    fn on_close() -> ();
                    /// Called by the host when the user saves settings in the plugin settings
                    fn on_setting_change(setting: _rt::String) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_lifecycle_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-load")] unsafe extern "C"
                        fn export_on_load(arg0 : * mut u8, arg1 : usize,) { unsafe {
                        $($path_to_types)*:: _export_on_load_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-close")] unsafe extern
                        "C" fn export_on_close() { unsafe { $($path_to_types)*::
                        _export_on_close_cabi::<$ty > () } } #[unsafe (export_name =
                        "thoth:plugin/plugin-lifecycle@0.1.0#on-setting-change")] unsafe
                        extern "C" fn export_on_setting_change(arg0 : * mut u8, arg1 :
                        usize,) { unsafe { $($path_to_types)*::
                        _export_on_setting_change_cabi::<$ty > (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_lifecycle_0_1_0_cabi;
            }
            /// ---------------------------------------------------------------------------
            /// Worlds — plugin authors implement one of these
            ///
            /// A world declares exactly which interfaces a plugin exports. Pick the
            /// world that matches your plugin's capabilities. If you implement multiple
            /// capabilities, implement the combined world or compose component binaries.
            /// ---------------------------------------------------------------------------
            /// ---------------------------------------------------------------------------
            /// plugin-settings — implement on every plugin (trivial no-op is fine)
            ///
            /// Lets a plugin own its settings UI. The host calls render-settings() once
            /// with the persisted key/value pairs; the plugin returns a UiNode tree.
            /// Events from the UI (text-input changes, button clicks, etc.) are forwarded
            /// back via handle-setting-event(). On Save the host calls get-settings() to
            /// read the current values for persistence, and calls apply-settings() on the
            /// next load so the plugin can restore its state.
            /// ---------------------------------------------------------------------------
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod plugin_settings {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginError = super::super::super::super::thoth::plugin::types::PluginError;
                #[derive(Clone)]
                pub struct SettingsOutput {
                    /// JSON-encoded UiNode tree (same DSL as ui-component).
                    pub node_json: _rt::String,
                    /// Height hint in logical pixels; 0 = auto.
                    pub height_hint: u32,
                }
                impl ::core::fmt::Debug for SettingsOutput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SettingsOutput")
                            .field("node-json", &self.node_json)
                            .field("height-hint", &self.height_hint)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_render_settings_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::render_settings();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let SettingsOutput {
                                node_json: node_json2,
                                height_hint: height_hint2,
                            } = e;
                            let vec3 = (node_json2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(height_hint2);
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::thoth::plugin::types::PluginError {
                                code: code4,
                                message: message4,
                            } = e;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(code4);
                            let vec5 = (message4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_render_settings<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Render the settings UI. Called once when the user opens the settings for this plugin.
                    fn render_settings() -> Result<SettingsOutput, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_thoth_plugin_plugin_settings_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "thoth:plugin/plugin-settings@0.1.0#render-settings")] unsafe
                        extern "C" fn export_render_settings() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_render_settings_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_thoth:plugin/plugin-settings@0.1.0#render-settings")]
                        unsafe extern "C" fn _post_return_render_settings(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_render_settings::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_thoth_plugin_plugin_settings_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_data_renderer_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::thoth::plugin::data_renderer::__export_thoth_plugin_data_renderer_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::data_renderer);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_meta::__export_thoth_plugin_plugin_meta_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::plugin_meta);
        $($path_to_types_root)*::
        exports::thoth::plugin::plugin_lifecycle::__export_thoth_plugin_plugin_lifecycle_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::thoth::plugin::plugin_lifecycle); $($path_to_types_root)*::
        exports::thoth::plugin::plugin_settings::__export_thoth_plugin_plugin_settings_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::thoth::plugin::plugin_settings);
    };
}
#[doc(inline)]
pub(crate) use __export_data_renderer_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:thoth:plugin@0.1.0:data-renderer-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 983] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xcc\x06\x01A\x02\x01\
A\x0c\x01B\x0a\x01m\x08\x0bfile-loader\x0bfile-viewer\x0bdata-source\x08exporter\
\x0fsearch-provider\x10new-ui-component\x0ddata-producer\x08renderer\x04\0\x0aca\
pability\x03\0\0\x01p\x01\x01ks\x01r\x08\x02ids\x04names\x07versions\x0bdescript\
ions\x0ccapabilities\x02\x06author\x03\x08homepage\x03\x04icon\x03\x04\0\x0bplug\
in-info\x03\0\x04\x01r\x02\x04codey\x07messages\x04\0\x0cplugin-error\x03\0\x06\x01\
r\x02\x03keys\x05values\x04\0\x0csetting-data\x03\0\x08\x03\0\x18thoth:plugin/ty\
pes@0.1.0\x05\0\x02\x03\0\0\x0cplugin-error\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0c\
plugin-error\x03\0\0\x01@\0\0s\x04\0\x04name\x01\x02\x01j\x01s\x01\x01\x01@\x01\x0c\
records-jsons\0\x03\x04\0\x06render\x01\x04\x04\0\x20thoth:plugin/data-renderer@\
0.1.0\x05\x02\x02\x03\0\0\x0bplugin-info\x01B\x04\x02\x03\x02\x01\x03\x04\0\x0bp\
lugin-info\x03\0\0\x01@\0\0\x01\x04\0\x08get-info\x01\x02\x04\0\x1ethoth:plugin/\
plugin-meta@0.1.0\x05\x04\x01B\x05\x01@\x01\x07settings\x01\0\x04\0\x07on-load\x01\
\0\x01@\0\x01\0\x04\0\x08on-close\x01\x01\x04\0\x11on-setting-change\x01\0\x04\0\
#thoth:plugin/plugin-lifecycle@0.1.0\x05\x05\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0c\
plugin-error\x03\0\0\x01r\x02\x09node-jsons\x0bheight-hinty\x04\0\x0fsettings-ou\
tput\x03\0\x02\x01j\x01\x03\x01\x01\x01@\0\0\x04\x04\0\x0frender-settings\x01\x05\
\x04\0\"thoth:plugin/plugin-settings@0.1.0\x05\x06\x04\0'thoth:plugin/data-rende\
rer-plugin@0.1.0\x04\0\x0b\x1a\x01\0\x14data-renderer-plugin\x03\0\0\0G\x09produ\
cers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
